---
# This playbook will deploy the node app container. It requires docker to be installed (by running the docker module first)

- name: Ensure Docker started
  service: name=docker enabled=yes state=started

- name: Fetch and deploy docker node container
  docker:
    name: simple-node
    image: ananthpr/simple-node-container
    state: reloaded
    docker_api_version: 1.18
    net: bridge
    pull: always
    volumes:
    - "/opt/logs/node:/var/log/node:rw"
    ports:
    - "4242:8080"

